function [fitresult, gof] = createFit(wwzz)
%CREATEFIT(WWZZ)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: wwzz
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Nov-2018 19:47:46


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], wwzz );

% Set up fittype and options.
ft = fittype( 'gauss4' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [132.75846094 1773 134.923708659272 126.699814427146 1522 117.962724531341 117.840932648423 1184 92.018311965428 106.847239922242 1011 99.8384694087704];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'wwzz', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
ylabel wwzz
grid on
